services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scheduler_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: ./apps/api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  scheduler:
    build: ./apps/scheduler
    depends_on:
      - postgres
      - redis

  worker:
    build: ./apps/worker
    depends_on:
      - postgres
      - redis
